### 20200309
---

Jest에서 E2E 테스트를 진행 도중 아래와 같은 오류가 발생했다. 신기한 것은 이 오류가 발생하고 다시 실행하면 오류가 발생하지 않는 것이다.

```
Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout
```

테스트 시간이 오래걸리면서 미리 콜백이 되면서 오류가 발생하는 것 같았다.

`done();` 콜백을 호출 해야한다. 그렇지 않으면 단순히 테스트를 통과하지 않는다.

```typescript
beforeAll((done /* call it or remove it*/) => {
  done(); // calling it
});
```

`done()` 콜백이 있는 다른 모든 함수에 적용된다.

---
#### 참고

https://stackoverflow.com/questions/49603939/async-callback-was-not-invoked-within-the-5000ms-timeout-specified-by-jest-setti